apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::588763412143:role/eksctl-eksctl-flask-app-nodegroup-NodeInstanceRole-1KYX8L2E91MAN
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::588763412143:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-09-08T16:03:55Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1702"
  uid: f999ce98-77e4-4b37-8caf-f8f0fdce2903
